name: Deploy Live Update
on:
  push:
    branches:
      - native
jobs:
  upload-file:
    runs-on: ubuntu-latest
    env:
      # Add your environment variables here
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Change directory to example-app
        run: cd example-app
      - name: Install dependencies
        run: npm install
      - name: Build web assets
        run: npm run build
      - name: Upload Live Update
        run: |
          npx laracap-cli apps:bundles:create \
            --path ${{ github.workspace }}/example-app/dist \
            --server "${{ secrets.LARACAP_SERVER_URL }}" \
            --token "${{ secrets.LARACAP_TOKEN }}" \
            --app-id 019dc873-ec06-7274-a7ee-59afd76c88e3 \
            --name "${{ github.ref }}" \
            --channel beta